name: cocreacion
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  esys_flutter_share: ^1.0.2

  flutter_slidable: ^0.5.3
  animated_text_kit: ^1.3.1
  font_awesome_flutter:
  generic_bloc_provider: ^1.0.9
  share: ^0.6.2+1
  agora_rtc_engine: ^0.9.9
  flutter_fluid_slider: ^1.0.1
  flutter_circular_chart: ^0.1.0
  palette_generator: ^0.2.0
  circle_list: ^1.0.0
  liquid_progress_indicator: ^0.3.2
  flutter_staggered_grid_view: ^0.3.0
  video_player: ^0.10.2
  country_pickers: ^1.1.0
  flushbar: ^1.8.2
  flutter_facebook_login: ^3.0.0
  flutter_auth_buttons: ^0.5.0
  percent_indicator: "^2.1.1"
  rxdart: ^0.22.2
  shared_preferences: ^0.5.3+4
  firebase_database: ^3.0.7
  story_view: ^0.10.0
  flutter_stories:
  flutter_simple_video_player: ^0.0.9
  image_picker: ^0.6.1+4
  gallery_saver: ^1.0.2
  toast: ^0.1.5
  flare_flutter: ^1.5.13
  flutter_local_notifications: ^0.8.4
  wc_flutter_share: ^0.1.1

  http: ^0.12.0+2
  preload_page_view: ^0.1.4

  cached_network_image: ^2.0.0-rc

  countdown: ^0.1.0
  fluttertoast: ^3.1.0
  provider:
  intl: ^0.16.0
  loading: ^1.0.1





  #  chewie: ^0.9.7



  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth:
  google_sign_in:
  firebase_storage: ^3.0.3
  cloud_firestore: ^0.12.7
  flutter_spinkit: "^4.0.0"
  flutter_bloc: ^0.21.0
  equatable: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/Like heart.flr
    - assets/heart.png
    - assets/heart_filled.png
    - assets/sprinkle.png
    - assets/Sprinkle.psd
    - assets/python.json
    - assets/test.json
    - assets/videos/test.MP4
    - assets/image/pict.jpg
    - assets/image/twitter.jpg
    - assets/image/video.jpg





  fonts:
    - family: Horizon
      fonts:
        - asset: fonts/Horizon.ttf
        - asset: fonts/Horizon.ttf

    - family: Niagara
      fonts:
        - asset: fonts/Niagara.TTF

    - family: Aileron
      fonts:
        - asset: fonts/Aileron-Thin.ttf


    - family: AileronBold
      fonts:
        - asset: fonts/Aileron-Bold.ttf

    - family: CustomIcons
      fonts:
        - asset: fonts/Iverus.ttf

    - family: CarmenSans
      fonts:
        - asset: fonts/StudioJASO - Carmen Sans Light.ttf

    - family: CarmenSansBold
      fonts:
        - asset: fonts/StudioJASO - Carmen Sans Bold.ttf




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
