/// Flutter icons Iverus
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iverus
///      fonts:
///       - asset: fonts/Iverus.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class Iverus {
  Iverus._();

  static const _kFontFam = 'Iverus';

  static const IconData heart_circled = const IconData(0xe800, fontFamily: _kFontFam);
}
